<a href="https://colab.research.google.com/github/AniketP04/PyTorch/blob/main/Tensors_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
def activation(x):
    """ Sigmoid activation function

        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

**Features are 5 random normal variables**

Creates a tensor with shape `(1, 5)`, one row and five columns, that contains values randomly distributed according to the normal distribution with a mean of zero and standard deviation of one.

In [3]:
features = torch.randn((1, 5))
features

tensor([[-0.5588,  2.4006,  1.1751, -0.7883, -1.9529]])

**True weights for our data, random normal variables again**

Creates another tensor with the same shape as features, again containing values from a normal distribution.

In [4]:
weights = torch.randn_like(features)
weights

tensor([[-0.8316,  0.6734, -0.6952, -0.7985,  0.4397]])

**A true bias term**

Creates a single value from a normal distribution.

In [5]:
bias = torch.randn((1, 1))
bias

tensor([[-0.1733]])

**Activation function**

In [6]:
y = activation(torch.sum(features * weights) + bias)
y

tensor([[0.7030]])

A matrix multiplication of the features and the weights `torch.mm()` or `torch.matmul()`. Remember that for matrix multiplications, the number of columns in the first tensor must equal to the number of rows in the second column.

To see the shape of a tensor called tensor, use `tensor.shape`

`weights.reshape(a, b)`: will return a new tensor with the same data as weights with size `(a, b)` sometimes, and sometimes a clone, as in it copies the data to another part of memory.

`weights.resize_(a, b)`: returns the same tensor with a different shape. However, if the new shape results in fewer elements than the original tensor, some elements will be removed from the tensor (but not from memory). If the new shape results in more elements than the original tensor, new elements will be uninitialized in memory

`weights.view(a, b)`: will return a new tensor with the same data as weights with size `(a, b)`.

In [7]:
y = activation(torch.mm(features, weights.view(5,1)) + bias)
y

tensor([[0.7030]])

###Numpy to Torch and back

To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [8]:
import numpy as np

a= np.random.rand(4,3)
a

array([[0.03147877, 0.46657798, 0.75892186],
       [0.31670173, 0.0236164 , 0.48573843],
       [0.14968776, 0.1620584 , 0.63982608],
       [0.29173545, 0.49258585, 0.72930337]])

In [9]:
b= torch.from_numpy(a)
b

tensor([[0.0315, 0.4666, 0.7589],
        [0.3167, 0.0236, 0.4857],
        [0.1497, 0.1621, 0.6398],
        [0.2917, 0.4926, 0.7293]], dtype=torch.float64)

In [10]:
b.numpy()

array([[0.03147877, 0.46657798, 0.75892186],
       [0.31670173, 0.0236164 , 0.48573843],
       [0.14968776, 0.1620584 , 0.63982608],
       [0.29173545, 0.49258585, 0.72930337]])

In [11]:
b.mul_(2)

tensor([[0.0630, 0.9332, 1.5178],
        [0.6334, 0.0472, 0.9715],
        [0.2994, 0.3241, 1.2797],
        [0.5835, 0.9852, 1.4586]], dtype=torch.float64)